name: ray-ascend ci

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: linux-aarch64-a3-2
    container:
      image: swr.cn-southwest-2.myhuaweicloud.com/base_image/ascend-ci/cann:8.2.rc1-a3-ubuntu22.04-py3.11
    strategy:
      matrix:
        python-version: ["3.11"]
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Build Python ${{ matrix.python-version }} wheel
        run: |
          echo "Building for Python ${{ matrix.python-version }}..."
          pip${{ matrix.python-version }} install build
          pip${{ matrix.python-version }} install -r requirements.txt
          python${{ matrix.python-version }} -m build --wheel
          pip${{ matrix.python-version }} install "$(ls dist/*.whl)[test,yr]" --force-reinstall
      - name: Run tests for Python ${{ matrix.python-version }}
        run: |
          echo "Running tests for Python ${{ matrix.python-version }}..."
          python${{ matrix.python-version }} -m pytest -v tests/

  build-docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Build documentation
        run: |
          pip install -r docs/requirements-docs.txt
          python -m mkdocs build -f docs/mkdocs.yml
